buildings_file: data/geojson/hausumringe_with_gebaeudeid.geojson
osm_file: data/osm/branitzer_siedlung.osm
demographics_file: data/json/building_population_resultsV6.json
scenario_config_file: branitz_scenarios.yaml
run_data_preparation: true
run_building_attributes: true
run_envelope_and_uvalue: true
run_demand_calculation: true
run_profile_generation: true
run_network_construction: true
run_scenario_manager: true
run_simulation_runner: true
run_kpi_calculator: true
run_llm_reporter: true
llm_model: gpt-4o
openai_api_key: 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
output_dir: results_test/
test_mode: true
selected_buildings:
- DEBBAL520000wau3
- DEBBAL520000watE
- DEBBAL520000wau5
- DEBBAL520000watF
- DEBBAL520000watG
- DEBBAL520000watD
- DEBBAL520000waun
- DEBBAL520000waul
- DEBBAL520000w9DK
- DEBBAL520000w9DJ
- DEBBAL520000w9DN
- DEBBAL520000w9DL
- DEBBAL520000w9DM
- DEBBAL520000w9Dr
profile_type: H0
